### ISSUE TITLE
Widget just sits there

### ISSUE THREAD

**Issue by everythingeeb** [enielrodriguez/optimus-gpu-switcher#35]
It doesn't let me open it to make changes. If I click nothing happens. If I right click and try to change settings nothing happens either.

**Comment by ratan00** [comment]
Did you try  command line envycontrol is it working ther?

I am using debian 12 installed in yesterday 
had to go through a lot to get  nvidia working see if that is an issue

also when i tried to add this widget from zip downloaded from store using add widget it is registered in the menu but it didn't work at all it just increases in widget count and is not showing up anywhere(panel/desktop)

kpackagetools6 doesn't exist in my kde kpackagetools5 does which i found from applet dev guide

But what did work was when i uninstalled all installed packages, using kpackagetools ,of this widget and installed it from discover store all instances showed up and applet is working

**Comment by enielrodriguez** [comment]
Hello! Please, when you report an error, it would be very helpful if you gave more context, for example widget version, Linux distribution and its version, KDE version, and any other details that allow us to reproduce the error.
That said, this bug is very similar to one already fixed in the latest version, please make sure you have it installed.

**Comment by everythingeeb** [comment]
Oh just checked it's fixed now. Hooray :)
